services:
  - type: web
    name: SAINI TXT DIRECT 
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/nikhilsaini098/Saini-txt-direct
    branch: main
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: API_ID
        sync: true
      - key: API_HASH
        sync: true
      - key: WEBHOOK
        sync: true
      - key: PORT
        value: 8000  # Default port value, update if needed
